### ISSUE TITLE
Support for port option

### ISSUE THREAD

**Issue by farski** [Dj-Codeman/doge#4]
`dog` never supported specifying a port for a query, which made things like `dig -p 5353 fileserver.local @224.0.0.251` impossible, though this can be helpful when dealing with mDNS queries. Having support for ports would be great.

**Comment by Dj-Codeman** [comment]
Give a508338 a look, Upd, Tcp, Tls and Https can called with the '**-p**' option to specify a port. 
**Ex:** 'doge -H @https://cloudflare-dns.com/dns-query google.com A AAAA -p 443'
