### ISSUE TITLE
IPv6: Add AAAA name support

### ISSUE THREAD

**Issue by brian6932** [Dj-Codeman/doge#56]
Would complete IPv6 support, currently `0.2.8-beta` only responds with A names.

**Comment by Dj-Codeman** [comment]
Hey, I don't quite get what your talking about. Is this outside of using the `AAAA` flag ?

**Comment by brian6932** [comment]
I rebuilt from the latest master with `with_https` and it seems to work, so I'm not sure if something here https://github.com/Dj-Codeman/doge/compare/v0.2.8-beta...v0.2.8 was at fault, or the `--features with_https` flag was required.

**Comment by Dj-Codeman** [comment]
> I meant within the command without args, as that's how most dns querying programs I've used work. [`dig`](https://man.voidlinux.org/dig.1), [`Resolve-DnsName`](https://learn.microsoft.com/powershell/module/dnsclient/resolve-dnsname), [`q`](https://github.com/natesales/q), and [`nslookup`](https://learn.microsoft.com/windows-server/administration/windows-commands/nslookup).

I changed it last night I didn't see that behavior using Dig, but it made sense.
